### PR TITLE
add test, and a kind of fix demo

### PR DESCRIPTION
**Pull request by mmouterde**
reproduce #30, but is not a fix for all use case.
I suggest to always escape all column names in generated SQL statments ?!

### CODE REVIEW

**Comment by jepiqueau** [comment]
@mmouterde You must not used  reserved words as column name. jeep-sqlite is used as the web part of the @capacitor-community/sqlite and cannot be modify without doing the same modifications in the native part of the plugin. I will reject this pull request

**Comment by mmouterde** [comment]
Native parts already support such column name

**Comment by jepiqueau** [comment]
@mmouterde i will test it and if native platforms support it i will take your PR for the next release

**Comment by jepiqueau** [comment]
@mmouterde This does not work in any of the Native platforms. So you must not use `reserved words`. This issue is definitively closed.

**Comment by mmouterde** [comment]
This does not work in any of the Native platforms.

Sorry, my bad. I commented the table that has `index` column to explore further with keep-sqlite... So android/ios did not crash...

**Comment by jepiqueau** [comment]
Can you give me the table schema so i can test on what you have

**Comment by mmouterde** [comment]
Hum, I'm confused, I'm not sure to have been clear in my last message, I agreed with you assertion.
As you said : Android implementation does not support reserved world too.


Anyway here it is : 
```sql
CREATE TABLE IF NOT EXISTS bundles (
      id TEXT PRIMARY KEY NOT NULL,
      projectId TEXT,
      name TEXT,
      "index" INTEGER,
      last_modified INTEGER DEFAULT (strftime('%s', 'now')),
      sql_deleted INTEGER DEFAULT 0 CHECK (sql_deleted IN (0, 1))
    );
```

**Pull request closed without merging**
